config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'redeem_requests/index'
  end

  namespace :admin do
  get 'reports/items'
  end

  namespace :admin do
  get 'reports/users'
  end

  namespace :admin do
  get 'notifications/index'
  end

  root 'invitations#landing'
  namespace 'admin' do
    resources :users do
      collection do
        post 'filter_user'
        get 'filter_user'
        get 'option_user'
      end
    end
    resources :payments
    resources :items do
      collection do
        post 'filter_item'
        get 'option_item'
      end
    end
    resources :invitations do
      collection do
        post 'send_mail'
        post 'filter_invite'
        get 'option_invite'
        delete 'destroy_multiple'
        get "sort_data"
      end
    end
    resources :item_categories
    resources :orders do
      collection do
        post 'filter_order'
        get 'filter_order'
        get 'option_order'
      end
    end
    resources :images
    resources :notifications
    resources :reports do
      collection do
        post 'filter_user'
        get 'option_user'
        post 'filter_item'
        get 'option_item'
      end
      member do
        get 'edit_item'
        get 'edit_user'
        put 'update_item'
        put 'update_user'
        get 'user_mail'
        get 'item_mail'
        delete 'delete_user'
        delete 'delete_item'
      end
    end
    resources :redeem_requests do
      collection do
        post 'filter_redeem'
        get 'option_redeem'
      end
    end
    get 'index' => 'admins#index'
    get 'logout' => 'devise/sessions#destroy'
    get "items/users/:id" => "items#user_items"
    get "orders/users/:id" => "orders#user_orders", as: :user_order
    get ":id/:follow_type" => "users#index", as: :user_follow
  end

  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin'}, :controllers => {:sessions => "admin/sessions", :registrations => "admin/registrations", :passwords => "admin/passwords"}
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => :registrations
  resources :invitations do
    collection do
      post 'mail_invite'
      get 'invite_username'
      get "invited_username"
      get 'valid_user'
    end
  end
  put 'invitation_username/:id' => "invitations#invitation_username", :as => :invitation_username
  get "invite_friend" => "invitations#invite_friend"
  get "invite_friend/:id" => "invitations#invite_friend"
  get "reset_password" => "home#reset_password", :as => :reset_password
  put "update_password/:moch" => "home#update_password", :as => :update_password
  get "privacy" => "invitations#privacy"
  get "terms" => "invitations#terms"
  get "/:permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#show"

  get "/:permalink/:item_permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    item_permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#detail"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
	before_save :send_time
	def admin_notification_mail(params)
  	# send_mail = SubscribeUserToMailingListJob.perform_later('yana.rahadhian@wgs.co.id')
  	user_mail = User.all.pluck(:email)
  	user_mail.each do |nm|
  		self.notif_date = self.notif_date.advance(seconds: 10)
			notif_mailer = NotificationMailer.delay(run_at: self.notif_date).notif_email(nm, params[:message])
		end
  end

  def send_time
  	_time = Time.now.strftime("%H:%M:%S")
  	self.notif_date = (self.notif_date.to_datetime + Time.parse("#{_time}").seconds_since_midnight.seconds).advance(:hours => -7)
  end

  def notif_parse(params)
    parse_object = $parse_client.object("Nofification")
    parse_object["description"] = self.description
    result = parse_object.save
  end
end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::AdminsController
  layout 'admin'
  require 'parse-ruby-client'
  def index
  	@notifs = Notification.order("created_at desc").page(params[:page]).per(25)
  	@notif = Notification.new
  end

  def edit
  	@notif = Notification.find_by_id(params[:id])
  	respond_to do |f|
  		f.js
  	end
  end

  def new
  	@notif = Notification.new
  	respond_to do |f|
  		f.js
  	end
  end

  def create
  	@notif = Notification.new(params_notif)
  	if @notif.save
      if @notif.present?
        @notif.notif_parse(params)
      end
      redirect_to admin_notifications_path
    else
      flash[:error] = "Data not valid!!"
      redirect_to admin_notifications_path
    end
  end

  def update
  	@notif = Notification.find_by_id(params[:id])
  	if @notif.update(params_notif)
      if @notif.present?
        @notif.notif_parse(params)
      end
      redirect_to admin_notifications_path
    else
      redirect_to admin_notifications_path
    end
  end

  def destroy
  	@notif = Notification.find_by_id(params[:id])
    if @notif.destroy
        flash[:notice] = "Success Delete a Records"
        redirect_to admin_notifications_path
    else
        flash[:error] = "fails delete a records"
        redirect_to admin_notifications_path
    end
  end

  private

  def params_notif
    params.require(:notification).permit(:notif_date, :description)
  end

end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/views/admin/notifications/_form.html.erb
<div class="modal-dialog-notif">      
  <!-- Modal content-->
  <%= form_for [:admin, @notif] do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Notification Mail</h4>
      </div>
      <div class="modal-body">
        <div class="row-fluid">
          <div class="span8">
            <div class="control-group">
              <div class="controls">
                <%#= text_field_tang 'datenotif' nil, class: 'form-control', 'data-behaviour' => 'datepicker' %>
                <%= f.text_field :notif_date, :class => 'datepicker' %>
              </div>              
            </div>
          </div>
        </div>    
        <%= f.text_area :description %>
      </div>
      <div class="modal-footer">
        <!-- <button type="submit" class="btn btn-info btn-lg" data-dismiss="modal">Send Mail</button> -->
        <%= f.submit 'Send Notif' %>
      </div>
    </div> 
  <% end %>     
</div>

app/views/admin/notifications/_notif_list.html.erb
<div class="table-responsive">
  <table id="example1" class="table table-striped table-hover table-responsive">
    <thead>
      <tr>
        <th class="col-md-3">Date</th>
        <th class="col-md-3">Time</th>
        <th class="col-md-3">Message</th>
        <th class="col-md-3">Action</th>
      </tr>
    </thead>
    <tbody>
    <% unless @notifs.empty? %>
      <% @notifs.each do |i| %>
        <tr>
          <td><%= i.notif_date.localtime.strftime("%d/%m/%Y") %></td>
          <td><%= i.notif_date.localtime.strftime("%H:%M:%S") %></td>
          <td><%= i.description %></td>
          <td>
          <%= link_to 'Resend',  edit_admin_notification_path(i), :remote => true  %> |
          <%= link_to 'Delete', admin_notification_path(i.id), method: "DELETE", data: {confirm: 'Are you sure delete ?'}, :class => "button-notif" %>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td colspan="4">No Record!</td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Create Notifications',  new_admin_notification_path, :remote => true, :class => "btn btn-info btn-lg"  %>
</div>

<div class="modal fade" id="myModal1" role="dialog">
  <%= render :partial => 'form'%>
</div>

app/views/admin/notifications/edit.js.erb
$("#myModal1").modal("show");
$("#myModal1").html("<%= j render "form"%>");
$(".datepicker").datepicker({format: 'dd/mm/yyyy'});

app/views/admin/notifications/index.html.erb
<div class="page-content">
  <div class="page-header position-relative">
    <h1>
      Notifications
      <small>
        <i class="fa fa-angle-double-right"></i>
        list
      </small>
    </h1>
  </div><!--/.page-header-->

  <div class="row-fluid">
    <div class="span12">
      <!--PAGE CONTENT BEGINS-->
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Push Notification</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <%= render :partial => 'notif_list'%>
          <%= paginate @notifs %>
        </div><!-- /.box-body -->
      </div>
    </div><!--/.span-->
  </div><!--/.row-fluid-->
</div><!--/.page-content-->
<%= content_for(:extra_js) do %>
  <!--[if IE]>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <![endif]-->

  <!--[if !IE]>-->

  <script type="text/javascript">
    window.jQuery || document.write("<script src='/assets/admin/jquery-2.0.3.min.js'>"+"<"+"/script>");
  </script>

  <!--<![endif]-->

  <!--[if IE]>
  <script type="text/javascript">
  window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
  </script>
  <![endif]-->

  <script type="text/javascript">
    if("ontouchend" in document) document.write("<script src='/assets/admin/jquery.mobile.custom.min.js'>"+"<"+"/script>");
  </script>

  <!--inline scripts related to this page-->

  <script type="text/javascript">
  	$(document).ready(function(){
      $('body').on('hidden.bs.modal', '.modal', function () {
        $(this).removeData('bs.modal');
      });

    });
  </script>
<% end %>

app/views/admin/notifications/new.js.erb
$("#myModal1").modal("show");
$("#myModal1").html("<%= j render "form"%>");
$(".datepicker").datepicker({format: 'dd/mm/yyyy'});