config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'redeem_requests/index'
  end

  namespace :admin do
  get 'reports/items'
  end

  namespace :admin do
  get 'reports/users'
  end

  namespace :admin do
  get 'notifications/index'
  end

  root 'invitations#landing'
  namespace 'admin' do
    resources :users do
      collection do
        post 'filter_user'
        get 'filter_user'
        get 'option_user'
      end
    end
    resources :payments
    resources :items do
      collection do
        post 'filter_item'
        get 'option_item'
      end
    end
    resources :invitations do
      collection do
        post 'send_mail'
        post 'filter_invite'
        get 'option_invite'
        delete 'destroy_multiple'
        get "sort_data"
      end
    end
    resources :item_categories
    resources :orders do
      collection do
        post 'filter_order'
        get 'filter_order'
        get 'option_order'
      end
    end
    resources :images
    resources :notifications
    resources :reports do
      collection do
        post 'filter_user'
        get 'option_user'
        post 'filter_item'
        get 'option_item'
      end
      member do
        get 'edit_item'
        get 'edit_user'
        put 'update_item'
        put 'update_user'
        get 'user_mail'
        get 'item_mail'
        delete 'delete_user'
        delete 'delete_item'
      end
    end
    resources :redeem_requests do
      collection do
        post 'filter_redeem'
        get 'option_redeem'
      end
    end
    get 'index' => 'admins#index'
    get 'logout' => 'devise/sessions#destroy'
    get "items/users/:id" => "items#user_items"
    get "orders/users/:id" => "orders#user_orders", as: :user_order
    get ":id/:follow_type" => "users#index", as: :user_follow
  end

  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin'}, :controllers => {:sessions => "admin/sessions", :registrations => "admin/registrations", :passwords => "admin/passwords"}
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => :registrations
  resources :invitations do
    collection do
      post 'mail_invite'
      get 'invite_username'
      get "invited_username"
      get 'valid_user'
    end
  end
  put 'invitation_username/:id' => "invitations#invitation_username", :as => :invitation_username
  get "invite_friend" => "invitations#invite_friend"
  get "invite_friend/:id" => "invitations#invite_friend"
  get "reset_password" => "home#reset_password", :as => :reset_password
  put "update_password/:moch" => "home#update_password", :as => :update_password
  get "privacy" => "invitations#privacy"
  get "terms" => "invitations#terms"
  get "/:permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#show"

  get "/:permalink/:item_permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    item_permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#detail"

end

app/views/shared/_footer.html.erb
<footer class="body-footer">
  <div class="container">
    <div class="col-xs-12">
      <div class="footer">
        <%= link_to "Register Your Interest", root_path + "#backgroundImage"  %>
        <%= mail_to "hello@tuckerbox.es" do %>
          Contact Us
        <% end %>
        <span>Tuckerbox &copy; <%= Time.now.year %></span>
        
        
        <%#= link_to "Why Use Tuckerbox?", root_path + "#whyTuckerbox" %>
        <%#= link_to "Why Use Tuckerbox?", root_path + "#whyTuckerbox" %>
        <%#= link_to "How Does Tuckerbox Work?", root_path + "#howtuckerbox" %>
        <%#= link_to "Privacy Policy", privacy_path %>
        <%#= link_to "Terms & Conditions", terms_path %>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default whiteSolid">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, :class => 'navbar-brand' do %>
        <%= image_tag "tuckbox_logo.png" %><strong class="small-gap-top">TUCKERBOX</strong>
      <% end %>
      <div id="social" class="nav pull-right menu">
        <ul class="nav nav-pills pull-right">
          <li role="presentation">
            <%= link_to "https://www.facebook.com/tuckerboxapp", target: "_blank" do%>
              <i class="fa fa-facebook"></i>
            <% end %>
          </li>
          <li role="presentation">
            <%= link_to "https://twitter.com/tuckerboxapp", target: "_blank" do%>
              <i class="fa fa-twitter"></i>
            <% end %>
          </li>
          <li role="presentation">
            <%= link_to "https://www.instagram.com/tuckerboxapp/", target: "_blank" do%>
              <i class="fa fa-instagram"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_header_admin.html.erb
<div class="navbar">
	<div class="navbar-inner">
		<div class="container-fluid">
			<!-- <a href="#" class="brand"> -->
				<small class="brand">
					<i class="fa fa-leaf"></i>
					TukerBox Admin
				</small>
			<!-- </a>/.brand -->

			<ul class="nav ace-nav pull-right">

				<li class="light-blue">
					<a data-toggle="dropdown" href="#" class="dropdown-toggle">
						<img class="nav-user-photo" src="/assets/profile-pic.jpg" alt="Jason's Photo" />
						<span class="user-info">
							<small>Welcome,</small>
							<%= current_admin.full_name %>
						</span>

						<i class="fa fa-caret-down"></i>
					</a>

					<ul class="user-menu pull-right dropdown-menu dropdown-yellow dropdown-caret dropdown-closer">
						<li>
							<%= link_to destroy_admin_session_path do %>
								<i class="fa fa-power-off"></i>
								Logout
							<% end %>
						</li>
					</ul>
				</li>
			</ul><!--/.ace-nav-->
		</div><!--/.container-fluid-->
	</div><!--/.navbar-inner-->
</div>

app/views/shared/_sidebar_admin.html.erb
<div class="sidebar" id="sidebar">
	<ul class="nav nav-list">
		<li class="<%= 'active' if controller?("admin/admins")%>">
			<%= link_to(admin_index_path) do %>
				<i class="fa fa-dashboard"></i>
				<span class="menu-text"> Dashboard </span>
			<% end %>
		</li>

		<li class="<%= 'active' if controller?("admin/users")%>">
			<%= link_to(admin_users_path) do %>
				<i class="fa fa-user"></i>
			  <span class="menu-text"> User </span>
			<% end %>
		</li>

		<li class="<%= 'active' if controller?("admin/items")%>">
			<%= link_to(admin_items_path) do %>
        <i class="fa fa-desktop"></i>
        <span class="menu-text"> Listing </span>
      <% end %>
		</li>

	 	<li class="<%= 'active' if controller?("admin/orders")%>">
      <%= link_to(admin_orders_path) do %>
        <i class="fa fa-list"></i>
        <span class="menu-text"> Orders </span>
      <% end %>
    </li>

		<li class="<%= 'active' if controller?("admin/item_categories")%>">
			<%= link_to(admin_item_categories_path) do %>
				<i class="fa fa-database"></i>
				<span class="menu-text"> Category </span>
			<% end %>
		</li>
    <li>
      <a href="#">
        <i class="fa fa-usd"></i>
        <span class="menu-text"> Revenue </span>
      </a>
    </li>
    <li class="<%= 'active' if controller?("admin/redeem_requests")%>">
    	<%= link_to(admin_redeem_requests_path) do %>
			  <i class="fa fa-credit-card"></i>
			  <span class="menu-text"> Redeem Request </span>
			<% end %>
	  </li><li class="<%= 'active' if controller?("admin/invitations")%>">
    	<%= link_to(admin_invitations_path) do %>
			  <i class="fa fa-envelope"></i>
			  <span class="menu-text"> Invitation Request </span>
			<% end %>
	  </li>
	  <li class="<%= 'active' if controller?("admin/notifications")%>">
    	<%= link_to(admin_notifications_path) do %>
			  <i class="fa fa-edit"></i>
			  <span class="menu-text"> Push Notification </span>
			<% end %>
	  </li>
	  <li class="dropdown <%= 'active' if controller?("admin/reports")%>">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      	<i class="fa fa-file-text"></i><span class="menu-text"> Report </span><i class="fa fa-fw fa-caret-down"></i>
      </a>
      <ul class="dropdown-menu forAnimate" role="menu">
        <li>
          <%= link_to(admin_reports_users_path) do %>
            <i class="fa fa-dot-circle-o"></i><span class="menu-text"> Users </span>
          <% end %>
        </li>
        <li>
          <%= link_to(admin_reports_items_path) do %>
            <i class="fa fa-dot-circle-o"></i><span class="menu-text"> Items </span>
          <% end %>
        </li>
      </ul>
    </li>   
	</ul><!--/.nav-list-->

	<div class="sidebar-collapse" id="sidebar-collapse">
		<i class="fa fa-chevron-circle-left" title="Hide Sidebar"></i>
	</div>
</div>

<%= content_for(:extra_js) do %>
	<script type="text/javascript">
		$(document).on("click", ".sidebar-collapse", function(){
			var res = $(".sidebar ul").hasClass("slide-sidebar")
			if (!res) {
				$('#sidebar-collapse i').prop('title', 'Show Sidebar');
			}else{
				$('#sidebar-collapse i').prop('title', 'Hide Sidebar');
			}
			res ? $(".main-content").removeClass("slide") : $(".main-content").addClass("slide");
			res ? $(".sidebar ul").removeClass("slide-sidebar") : $(".sidebar ul").addClass("slide-sidebar");
			res ? $(".sidebar-collapse i").addClass("fa-chevron-circle-left").removeClass("fa-chevron-circle-right") : $(".sidebar-collapse i").addClass("fa-chevron-circle-right").removeClass("fa-chevron-circle-left")
		})
	</script>
<% end %> 