config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'redeem_requests/index'
  end

  namespace :admin do
  get 'reports/items'
  end

  namespace :admin do
  get 'reports/users'
  end

  namespace :admin do
  get 'notifications/index'
  end

  root 'invitations#landing'
  namespace 'admin' do
    resources :users do
      collection do
        post 'filter_user'
        get 'filter_user'
        get 'option_user'
      end
    end
    resources :payments
    resources :items do
      collection do
        post 'filter_item'
        get 'option_item'
      end
    end
    resources :invitations do
      collection do
        post 'send_mail'
        post 'filter_invite'
        get 'option_invite'
        delete 'destroy_multiple'
        get "sort_data"
      end
    end
    resources :item_categories
    resources :orders do
      collection do
        post 'filter_order'
        get 'filter_order'
        get 'option_order'
      end
    end
    resources :images
    resources :notifications
    resources :reports do
      collection do
        post 'filter_user'
        get 'option_user'
        post 'filter_item'
        get 'option_item'
      end
      member do
        get 'edit_item'
        get 'edit_user'
        put 'update_item'
        put 'update_user'
        get 'user_mail'
        get 'item_mail'
        delete 'delete_user'
        delete 'delete_item'
      end
    end
    resources :redeem_requests do
      collection do
        post 'filter_redeem'
        get 'option_redeem'
      end
    end
    get 'index' => 'admins#index'
    get 'logout' => 'devise/sessions#destroy'
    get "items/users/:id" => "items#user_items"
    get "orders/users/:id" => "orders#user_orders", as: :user_order
    get ":id/:follow_type" => "users#index", as: :user_follow
  end

  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin'}, :controllers => {:sessions => "admin/sessions", :registrations => "admin/registrations", :passwords => "admin/passwords"}
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => :registrations
  resources :invitations do
    collection do
      post 'mail_invite'
      get 'invite_username'
      get "invited_username"
      get 'valid_user'
    end
  end
  put 'invitation_username/:id' => "invitations#invitation_username", :as => :invitation_username
  get "invite_friend" => "invitations#invite_friend"
  get "invite_friend/:id" => "invitations#invite_friend"
  get "reset_password" => "home#reset_password", :as => :reset_password
  put "update_password/:moch" => "home#update_password", :as => :update_password
  get "privacy" => "invitations#privacy"
  get "terms" => "invitations#terms"
  get "/:permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#show"

  get "/:permalink/:item_permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    item_permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#detail"

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  has_many :childrens, :class_name => "Invitation", :foreign_key => :inviter_id
  belongs_to :parent, :class_name => "Invitation", :foreign_key => :inviter_id

	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validate :ref_key, :on => :create
  validates :first_name, presence: :true, :on => :create
  validates :username, presence: :true, :on => :update
  validates :username, uniqueness: {:message => "Already taken"}, :on => [:update]
  validates_exclusion_of :username, in: %w( tuckerbox ), message: "Can’t use this username"
  validates :email, uniqueness: {:message => "Email has already been taken"}, :on => :create
  scope :username, -> { where("username LIKE '%#{params[:username]}%'")}
	private

  # def subscribe_user_to_mailing_list
  #   SubscribeUserToMailingListJob.perform_later(self)
  # end

  def self.admin_invitation_mail(params)
  	params[:tags_list].split(",").each do |um|
			invite_mailer = InvitationMailer.delay(run_at: 15.seconds.from_now).admin_email_invitation(um, params[:submail], params[:textarea])
		end
  end

  def self.filter(params, state, sort)
    conditions = []
    args = {}

    ["first_name", "status", "email", "username"].each do |k|
      if !params[k.to_sym].blank?
        conditions << "#{k} #{k == "status" ? "=" : "like"} :#{k}"
        args[k.to_sym] = k == "status" ? "#{params[k.to_sym]}" : "%#{params[k.to_sym]}%"
      end
    end
    
    state = "DESC" if state.nil?
    where(conditions.join(" AND "), args)
    .order("#{sort} #{state}")
    .page(params[:page]).per(params[:limit] == "All" ? Invitation.count : params[:limit])
  end

  def self.get_invited_records
    user_names = []

    file_path = Rails.root.join("sample_username.txt")
    File.open(file_path, "r").each_line do |line|
      user_names << line.gsub("\n", "")
    end

    user_names += Invitation.select("username").where("username IS NOT NULL").map(&:username)

    return user_names.shuffle[0..99]
  end

  def ref_key
    rand_text = Array.new(20){[*"A".."Z", *"0".."9"].sample}.join
    gen_base = Base64.encode64("#{rand_text}").first(20)
    self.ref_id = gen_base
  end

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/invitations_controller.rb
class Admin::InvitationsController < Admin::AdminsController
	layout 'admin'
	def index
    @state = "DESC"
    @invites = Invitation.all
	  @invite = Invitation.order("created_at DESC").page(params[:page]).per(25)
	end

	def send_mail
		@admin_mail = Invitation.admin_invitation_mail(params)
		redirect_to admin_invitations_path
	end

	def filter_invite
    @state = params[:sort_filter]
 	  @sort = params[:keyword].nil? ? "created_at" : "#{params[:keyword]}"
  	@invite = Invitation.filter(params, @state, @sort)
	end

	def option_invite	
 	  @sort = params[:keyword].nil? ? "created_at" : "#{params[:keyword]}"
  	@invite = Invitation.filter(params, params[:sort_filter], @sort)
	end

  def sort_data
    @state = params[:state] == "ASC" ? "DESC" : "ASC"
    @sort = params[:keyword].nil? ? "id" : "#{params[:keyword]}"
    @invite = Invitation.filter(params, @state, @sort)
  end

	def sort_column
    Invitation.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end

  def destroy
    @invite = Invitation.find(params[:id])
    if @invite.destroy
        flash[:notice] = "Success Delete a Records"
        redirect_to action: 'index'
    else
        flash[:error] = "Failed delete a records"
        redirect_to action: 'index'
    end
  end

  def destroy_multiple
  	if !params[:tag].blank?
  		Invitation.where("id IN (#{params[:tag].collect {|k,v| k }.join(",")})").destroy_all
  	end
  	respond_to do |format|
	  	format.html { redirect_to admin_invitations_path }
	  end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  layout 'application'
  skip_before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token
  include ApplicationHelper

  def index
  end

  def landing
  	@invitation = Invitation.new
    if !params[:f].blank?
      if params[:f] == "reserve_uname"
        @notif = "success"
      end
    end
  end

  def create
    @ref_id = Invitation.find_by_ref_id(params[:invitation][:ref_id])
    if @ref_id.nil?
      @invitation = Invitation.new(params_invitation)
    else
      @invitation = @ref_id.childrens.build(params_invitation)
    end
    @invitation.country = visitor_country
    if @invitation.save
      if @invitation.present?
        InvitationMailer.invite_email(@invitation).deliver_now
        flash[:notice] = "Registration Successful. #{@invitation.email} has been added to our database. Thank you!"
      else
        flash[:notice] = "Invitation Failed!"
      end
        render 'invite_friend'
    else
        flash[:notice] = "Email has already been taken!!"
        flash[:error] = "data not valid"
        render 'landing'
    end
  end

  def invitation_username
    @invitation = Invitation.find(params[:id])
    @invitation.username = params[:invitation][:username]
    respond_to do |f|
      if @invitation.save
        InvitationMailer.mail_booked_username(@invitation).deliver_now
        flash[:notice] = "Username #{@invitation.username} reserved"
        @notif = "success"
      end
      f.js
    end
  end

  def invited_username
    @user_names = Invitation.get_invited_records
    render json: @user_names
  end

  def mail_invite
    @invitation = Invitation.find(params[:invitation])
    @invitation.notes = params[:notes]
    InvitationMailer.mail_invite(params[:mail_to], params[:notes], @invitation).deliver_now
    flash[:notice] = "Invites sent. You're a trooper!"
    render 'invite_username'
    @notif = "success"
  end

  def invite_username
    @invitation = Invitation.find(params[:id])
    # render layout: false
  end

  def valid_user
    sample_username = File.open(Rails.root.to_s+"/sample_username.txt", "rb").read.split("\n")
    if sample_username.include?(params[:username])
      @msg = {:message => "Already taken", :status => "existed"}
    else
      if params[:username].to_s.downcase.match(/tuckerbox/).present?
          @msg = {:message => "Can’t use this username", :status => "existed"}
      else
        valid_invite = Invitation.where("username LIKE ?", "%#{params[:username]}%")
        valid_user = User.where("username LIKE ?", "%#{params[:username]}%")
        if valid_invite.present? || valid_user.present?
          @msg = {:message => "Already taken", :status => "existed"}
        else
          @msg = {:message => "Available", :status => "available" }
        end
      end
    end
    render :layout => false, :json => @msg, :status => @status
  end

  def privacy
    
  end

  def terms
    
  end

  def show
    @invitation = Invitation.find(params[:id])
    render 'invite_friend'
  end

  private
  def params_invitation
    params.require(:invitation).permit(:first_name, :country, :email, :status, :ref_id, :username, :inviter_id)
  end

end

app/views/admin/invitations/_invite_list.html.erb
<div class="table-responsive">
  <% unless @invite.empty? %>
    <%= form_tag destroy_multiple_admin_invitations_path, method: :delete, id: "multiDestroyForm" do %>
      <table id="" class="table table-bordered table-hover table-striped tablesorter">
        <thead>
          <tr id="header">
            <th class="col-md-1 check-invite">
              <%= check_box_tag('check_all', 'check_all', false) %>Select All
            </th>
            <th class="col-md-2">First Name</th>
            <th class="col-md-3">Email</th>
            <th class="col-md-2">Country</th>
            <th class="col-md-1"><%= link_to "Status", "#", :onClick => "SetSortRow('status'); return false;" %><i class="fa fa-sort pull-right"></th>
            <th class="col-md-1">Username</th>
            <th class="col-md-1"><%= link_to "Invite By", "#", :onClick => "SetSortRow('inviter_id'); return false;" %><i class="fa fa-sort pull-right"></th>
            <th class="col-md-2"><%= link_to "Create at", "#", :onClick => "SetSortRow('created_at'); return false;" %><i class="fa fa-sort pull-right"></th>
          </tr>
        </thead>
        <tbody>
          <% @invite.each do |i| %>
          <tr>
            <td class="check-invite"><%= check_box_tag("tag[#{i.id}]", i.email, false, { class: 'eula_check' }) %></td>
            <td><%= i.first_name %></td>
            <td><%= i.email %></td>
            <td><%= i.country %></td>
            <td><%= i.status %></i></td>
            <td><%= i.username %></i></td>
            <td><%= i.parent.try(:first_name) %></td>
            <td><%= i.created_at.strftime("%b %d %Y") %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <button type="button" id="emailBtn" class="btn btn-info btn-lg pull-left" data-toggle="modal" data-target="#myModal">Create Mail</button>
      <button type="button" id="multipleDestroy" class="btn btn-info btn-lg pull-left" style="margin-left: 20px;">Delete Selected Invitation</button>
    <% end %>
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">      
        <!-- Modal content-->
        <%= form_for "Invitation", :url => send_mail_admin_invitations_path, :id => "my_mail" do -%>
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Create Description of Mail</h4>
          </div>
          <div class="modal-body">
            <div class="row-fluid">
              <div class="span8">
                <div class="control-group">
                  <div class="controls">
                    <%= hidden_field_tag 'tags_list' %>
                    <%= text_field_tag 'submail', nil, class: 'form-control', placeholder: 'Subject', style: 'margin-bottom: 25px;' %>
                  </div>              
                </div>
              </div>
            </div>    
            <%= text_area_tag 'textarea', nil, :class => 'wysihtml5', :placeholder => "Enter text ...", :style => "font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; width: 710px;" %>
          </div>
          <div class="modal-footer">
            <!-- <button type="submit" class="btn btn-info btn-lg" data-dismiss="modal">Send Mail</button> -->
            <%= submit_tag 'Send Mail' %>
          </div>
        </div> 
        <% end %>     
      </div>
    </div>
  <% else %>
   <table id="example1" class="table table-striped table-hover table-responsive">
      <thead>
        <tr id="">
          <td colspan="5">No Record!</td>
        </tr>
      </thead>
    </table>
  <% end %>
</div>
<%= paginate @invite %>

<script type="text/javascript">
  $(document).ready(function(){
      $('.wysihtml5').each(function(i, elem) {
        $(elem).wysihtml5();
      });

      $( "#emailBtn" ).click(function() {
        var length_checked = $('.check-invite').find('input:checked').length
        // var arrayChecked = $('.check-invite').find('input:checked').val;
        if (length_checked > 0) {
          var val = [];
          $(':checkbox:checked').each(function(i){
            val.push($(this).val())
          });
          val.pop()
          $("#tags_list").val(val.join(","))        
        }
      });
    });

   function SetSortRow(state){
      $.ajax({
          data: {
            keyword: state,
            state: $(".sort_filter").val(),
            status: $(".status_filter").val(),
            first_name: $(".first_name_filter").val(),
            email: $(".email_filter").val(),
            username: $(".username_filter").val(),
            limit: $(".limit_filter").val(),
          },
          type: "get",
          url: "/admin/invitations/sort_data",
          success: function (data) {
          }
        });    
    }
</script>

app/views/admin/invitations/filter_invite.js.erb
$(".filter-content").html("<%= j render :partial => 'invite_list'%>");

app/views/admin/invitations/index.html.erb
<div class="page-content">
  <div class="page-header position-relative">
    <h1>
      Invitations
      <small>
        <i class="fa fa-angle-double-right"></i>
        list
      </small>
    </h1>
  </div><!--/.page-header-->

  <div class="row-fluid">
    <div class="span12">
      <!--PAGE CONTENT BEGINS-->
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">Invitations list | Total invited users: <%= @invites.count %></h3>
        </div><!-- /.box-header -->
        <div class=" box-body">
          <%= form_for "Invitation", :url => filter_invite_admin_invitations_path, :id => "", :remote => true do %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <span class="filter-left">Filters</span>
                <span class="filter-right">View Page</span>
              </div>
              <div class="panel-body">
                <div class="filter-left">
                  <div class="col-lg-2">
                    <div class="form-group input-group" style="margin:0">
                      <!-- <label>Status</label> -->
                     <%= select_tag(:status, options_for_select([ ["Eater", "Eater"], ["Feeder", "Feeder"] ] ),{:class => "form-control status_filter", :prompt => "All"})  %></td>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group input-group" style="margin:0">
                      <!-- <label>First Name</label> -->
                      <%= text_field_tag "first_name", "", :class => "form-control first_name_filter", :placeholder => "First Name" %>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group input-group" style="margin:0">
                      <!-- <label>Email</label> -->
                      <%= text_field_tag "email", "", :class => "form-control email_filter", :placeholder => "Email" %>
                    </div>
                  </div>
                  <div class="col-lg-3">
                    <div class="form-group input-group" style="margin:0">
                      <!-- <label>Username</label> -->
                      <%= text_field_tag "username", "", :class => "form-control username_filter", :placeholder => "Username" %>
                      <%= hidden_field_tag "sort_filter", @state, :class => "form-control sort_filter" %>
                    </div>
                  </div>
                </div>
                <div class="filter-right">
                  <div class="col-lg-2">
                    <div class="form-group input-group" style="margin:0">
                      <!-- <label>Status</label> -->
                     <%= select_tag(:limit, options_for_select([ ["All", "All"], ["5", "5"], ["10", "10"], ["25", "25"], ["50", "50"], ["100", "100"]], :selected=> "25"),{:selected => "25", :class => "form-control limit_filter"})  %></td>
                    </div>
                  </div>
                  <div class="col-lg-1">
                    <%= submit_tag "Apply",:class => "form-control btn btn-small"%>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="clearfix">&nbsp;</div>
        <div class="box-body filter-content">
          <%= render :partial => 'invite_list'%>
        </div><!-- /.box-body -->
      </div>
    </div><!--/.span-->
  </div><!--/.row-fluid-->
</div><!--/.page-content-->
<%= content_for(:extra_js) do %>
  <!--[if IE]>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <![endif]-->

  <!--[if !IE]>-->

  <script type="text/javascript">
    window.jQuery || document.write("<script src='/assets/admin/jquery-2.0.3.min.js'>"+"<"+"/script>");
  </script>

  <!--<![endif]-->

  <!--[if IE]>
  <script type="text/javascript">
  window.jQuery || document.write("<script src='assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
  </script>
  <![endif]-->

  <script type="text/javascript">
    if("ontouchend" in document) document.write("<script src='/assets/admin/jquery.mobile.custom.min.js'>"+"<"+"/script>");
  </script>

  <!--inline scripts related to this page-->

  <script type="text/javascript">
    $(document).on("click", "#multipleDestroy", function(){
      var checkedCount = $("tbody input[type='checkbox']:checked").length
      if( checkedCount == 0){
        alert("You must at least check 1 invitation")
      } else {
        c = confirm("Are you sure want to delete all the selected invitations from the database?")
        if(c){
          $("#multiDestroyForm").submit()
        }
      }
    })
    $(document).on("change", "#check_all", function(){
      $("tbody input[type='checkbox']").prop("checked", $(this).is(":checked"))
    })

    $(document).on("change", "tbody input[type='checkbox']", function(){
      var inputCount = $("tbody input[type='checkbox']").length
      var checkedCount = $("tbody input[type='checkbox']:checked").length

      $("#check_all").prop("checked", inputCount == checkedCount)
    })

    $(document).ready(function(){
      $('.wysihtml5').each(function(i, elem) {
        $(elem).wysihtml5();
      });
      $('body').on("click", ".pagination a", function(e){
        var state = $(".sort_filter").val();
        var status = $(".status_filter").val();
        var first_name = $(".first_name_filter").val();
        var email = $(".email_filter").val();
        var username = $(".username_filter").val();
        var limit = $(".limit_filter").val();

        $.get("/admin/invitations/option_invite?"+this.href.split("?")[1]+"&state="+ state +"&status="+ status +"&first_name="+ first_name +"&email="+ email +"&username="+ username +"&limit="+ limit, null, null, "script");
        return false;
      });
    })

    $(function() {
      var oTable1 = $('#sample-table-2').dataTable( {
      "aoColumns": [
          { "bSortable": false },
          null, null,null, null, null,
        { "bSortable": false }
      ] } );
      
      
      $('[data-rel="tooltip"]').tooltip({placement: tooltip_placement});
      function tooltip_placement(context, source) {
        var $source = $(source);
        var $parent = $source.closest('table')
        var off1 = $parent.offset();
        var w1 = $parent.width();
    
        var off2 = $source.offset();
        var w2 = $source.width();
    
        if( parseInt(off2.left) < parseInt(off1.left) + parseInt(w1 / 2) ) return 'right';
        return 'left';
      }
    })

    // $(function() {
    //   $('textarea#eg-textarea').editable({
    //     inlineMode: false
    //   })
    // });

    $( "#emailBtn" ).click(function() {
      var length_checked = $('.check-invite').find('input:checked').length
      // var arrayChecked = $('.check-invite').find('input:checked').val;
      if (length_checked > 0) {
        var val = [];
        $(':checkbox:checked').each(function(i){
          val.push($(this).val())
        });
        val.pop()
        $("#tags_list").val(val.join(","))        
      }
    });

  </script>
<% end %>

app/views/admin/invitations/index.js.erb
$(".filter-content").html("<%= j render :partial => 'invite_list'%>");

app/views/admin/invitations/option_invite.js.erb
$(".filter-content").html("<%= j render :partial => 'invite_list'%>");
$(".sort_filter").val("<%= @state %>");

app/views/admin/invitations/sort_data.js.erb
$(".filter-content").html("<%= j render :partial => 'invite_list'%>");
$(".sort_filter").val("<%= @state %>");