config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'redeem_requests/index'
  end

  namespace :admin do
  get 'reports/items'
  end

  namespace :admin do
  get 'reports/users'
  end

  namespace :admin do
  get 'notifications/index'
  end

  root 'invitations#landing'
  namespace 'admin' do
    resources :users do
      collection do
        post 'filter_user'
        get 'filter_user'
        get 'option_user'
      end
    end
    resources :payments
    resources :items do
      collection do
        post 'filter_item'
        get 'option_item'
      end
    end
    resources :invitations do
      collection do
        post 'send_mail'
        post 'filter_invite'
        get 'option_invite'
        delete 'destroy_multiple'
        get "sort_data"
      end
    end
    resources :item_categories
    resources :orders do
      collection do
        post 'filter_order'
        get 'filter_order'
        get 'option_order'
      end
    end
    resources :images
    resources :notifications
    resources :reports do
      collection do
        post 'filter_user'
        get 'option_user'
        post 'filter_item'
        get 'option_item'
      end
      member do
        get 'edit_item'
        get 'edit_user'
        put 'update_item'
        put 'update_user'
        get 'user_mail'
        get 'item_mail'
        delete 'delete_user'
        delete 'delete_item'
      end
    end
    resources :redeem_requests do
      collection do
        post 'filter_redeem'
        get 'option_redeem'
      end
    end
    get 'index' => 'admins#index'
    get 'logout' => 'devise/sessions#destroy'
    get "items/users/:id" => "items#user_items"
    get "orders/users/:id" => "orders#user_orders", as: :user_order
    get ":id/:follow_type" => "users#index", as: :user_follow
  end

  devise_for :admins, :path => '', :path_names => {:sign_in => 'admin'}, :controllers => {:sessions => "admin/sessions", :registrations => "admin/registrations", :passwords => "admin/passwords"}
  devise_for :users, path: "", path_names: { sign_in: 'login', sign_out: 'logout'}, :skip => :registrations
  resources :invitations do
    collection do
      post 'mail_invite'
      get 'invite_username'
      get "invited_username"
      get 'valid_user'
    end
  end
  put 'invitation_username/:id' => "invitations#invitation_username", :as => :invitation_username
  get "invite_friend" => "invitations#invite_friend"
  get "invite_friend/:id" => "invitations#invite_friend"
  get "reset_password" => "home#reset_password", :as => :reset_password
  put "update_password/:moch" => "home#update_password", :as => :update_password
  get "privacy" => "invitations#privacy"
  get "terms" => "invitations#terms"
  get "/:permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#show"

  get "/:permalink/:item_permalink",
    permalink: /[a-zA-Z0-9\-_\.]+?/,
    item_permalink: /[a-zA-Z0-9\-_\.]+?/,
    format: /html/,
    to: "home#detail"

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :reporter, :foreign_key => 'reporter_integer', :class_name => 'User'
 	belongs_to :report_category, :foreign_key => 'report_type_id', :class_name => 'ReportType'
 	belongs_to :report, :polymorphic => true
 	
end

app/models/report_type.rb
class ReportType < ActiveRecord::Base
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
	layout 'admin'
  def items
    @item = Item.where.not(:status => "active").page(params[:page]).per(25)
  end

  def users
    @user = User.where.not(:status => "active").page(params[:page]).per(25)
  end

  def edit_user
    @user = User.find(params[:id])
  end

  def edit_item
    @item = Item.find(params[:id])
  end

  def update_user
    @user = User.find(params[:id])
    @user.update_attribute(:status, params[:status])
    @user.reports.last.update_attribute(:reason, params[:reason])
  end

  def update_item
    @item = Item.find(params[:id])
    @item.update_attribute(:status, params[:status])
    @item.reports.last.update_attribute(:reason, params[:reason])
  end

  def user_mail
    @user = User.find(params[:id])
    ReportMailer.user_email(@user).deliver_now
    redirect_to admin_reports_users_path
  end

  def item_mail
    @item = Item.find(params[:id])
    ReportMailer.item_email(@item).deliver_now
    redirect_to admin_reports_items_path
  end

  def filter_user
    @sort = params[:keyword].nil? ? "id":"#{params[:keyword]}"
    @user = User.filter(params, @state, @sort).where.not(:status => "active")
  end

  def option_user
    @sort = params[:keyword].nil? ? "id":"#{params[:keyword]}"
    @user = User.filter(params, @state, @sort)
  end

  def filter_item
    @sort = params[:keyword].nil? ? "id":"#{params[:keyword]}"
    @item = Item.filter(params, @state, @sort).where.not(:status => "active")
  end

  def option_item
    @sort = params[:keyword].nil? ? "id":"#{params[:keyword]}"
    @users = Item.filter(params, @state, @sort)
  end

  def delete_user
    @user = User.find(params[:id])
    if @user.present?
      @user.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to admin_reports_users_path
    end
  end

  def delete_item
    @item = Item.find(params[:id])
    if @item.present?
      @item.destroy
      flash[:notice] = "Success Delete a Records"
      redirect_to admin_reports_items_path
    end
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/_form_item.html.erb
<td><%= @item.name %></td>
<td><%= link_to "#{WEB_URL}/#{@item.user.permalink}/#{@item.permalink}", "#{WEB_URL}/#{@item.user.permalink}/#{@item.permalink}", target: :blank %></td>
<td><%= @item.reports.collect{|r| r.comment}.join(", ")%></td>
<td><%= @item.reports.collect{|r| r.report_category.name }.uniq.join(", ") %></td>
<td><%= text_area_tag "reason[]", @item.reports.last.reason %></td>
<td><%= select_tag "item_status[]", options_for_select(["active", "suspend", "block"], @item.status), {:class => "form-control"} %></td>
<td class="center">
  <%= link_to 'Save', "javascript:void(0)", onclick: "update_report(this, #{@item.id})" %> |
  <%= link_to 'Cancel', edit_item_admin_report_path(@item.id, cancel: true), remote: true %>
</td>

app/views/admin/reports/_form_user.html.erb
<td><%= @user.full_name %></td>
<td><%= link_to "#{WEB_URL}/#{@user.permalink}", "#{WEB_URL}/#{@user.permalink}", target: :blank %></td>
<td><%= @user.reports.collect{|r| r.comment}.join(", ")%></td>
<td><%= @user.reports.collect{|r| r.report_category.name }.uniq.join(", ") %></td>
<td><%= text_area_tag "reason[]", @user.reports.last.reason %></td>
<td><%= select_tag "user_status[]", options_for_select(["active", "suspend", "block"], @user.status), {:class => "form-control"} %></td>
<td class="center">
  <%= link_to 'Save', "javascript:void(0)", onclick: "update_report(this, #{@user.id})" %> |
  <%= link_to 'Cancel', edit_user_admin_report_path(@user.id, cancel: true), remote: true %>
</td>

app/views/admin/reports/_item.html.erb
<tr id="item<%=i.id%>">
  <td><%= i.name %></td>
  <td><%= link_to "#{WEB_URL}/#{i.user.permalink}/#{i.permalink}", "#{WEB_URL}/#{i.user.permalink}/#{i.permalink}", target: :blank %></td>
  <td><%= i.reports.collect{|r| r.comment}.join(", ")%></td>
  <td><%= i.reports.collect{|r| r.report_category.name }.uniq.join(", ") %></td>
  <td><%= i.reports.collect{|r| r.reason}.join() %></td>
  <td><%= i.status %></td>
  <td class="center">
    <%= link_to "Send Mail", item_mail_admin_report_path(i.id) %> |
    <%= link_to 'Edit', edit_item_admin_report_path(i.id), remote: true %> | 
    <%= link_to 'Delete', delete_item_admin_report_path(i.id), data: {confirm: 'Are you sure delete Record item!?'},  method: :delete %>
  </td>
</tr>

app/views/admin/reports/_item_list.html.erb
<div class="table-responsive">
  <% unless @item.empty? %>
    <table id="" class="table table-bordered table-hover table-striped tablesorter">
      <thead>
        <tr id="header">
          <th class="col-md-1">Name</th>
          <th class="col-md-2">URL</th>
          <th class="col-md-2">Comment</th>
          <th class="col-md-2">Report Type</th>
          <th class="col-md-2">Reason</th>
          <th class="col-md-1">Status</th>
          <th class="col-md-3">Action</th>            
        </tr>
      </thead>
      <tbody>
        <% @item.each do |i| %>
          <%= render :partial => 'item', :locals => {:i => i} %>
        <% end %>
      </tbody>
    </table>
  <% else %>
   <table id="example1" class="table table-striped table-hover table-responsive">
      <thead>
        <tr id="">
          <td colspan="5">No Record!</td>
        </tr>
      </thead>
    </table>
  <% end %>
</div>
<%= paginate @item %>

app/views/admin/reports/_user.html.erb
<tr id="user<%=u.id%>">
  <td><%= u.full_name %></td>
  <td><%= link_to "#{WEB_URL}/#{u.permalink}", "#{WEB_URL}/#{u.permalink}", target: :blank %></td>
  <td><%= u.reports.collect{|r| r.comment}.join(", ")%></td>
  <td><%= u.reports.collect{|r| r.report_category.name }.uniq.join(", ") %></td>
  <td><%= u.reports.collect{|r| r.reason}.join() %></td>
  <td><%= u.status %></td>
  <td class="center">
    <%= link_to "Send Mail", user_mail_admin_report_path(u.id) %> |
    <%= link_to 'Edit', edit_user_admin_report_path(u.id), remote: true %> | 
    <%= link_to 'Delete', delete_user_admin_report_path(u.id), data: {confirm: 'Are you sure delete Record user!?'},  method: :delete %>
  </td>
</tr>

app/views/admin/reports/_user_list.html.erb
<div class="table-responsive">
  <% unless @user.blank? %>
    <table id="" class="table table-bordered table-hover table-striped tablesorter">
      <thead>
        <tr id="header">
          <th class="col-md-1">User Name</th>
          <th class="col-md-2">URL</th>
          <th class="col-md-2">Comment</th>
          <th class="col-md-2">Report Type</th>
          <th class="col-md-2">Reason</th>
          <th class="col-md-1">Status</th>
          <th class="col-md-3">Action</th>            
        </tr>
      </thead>
      <tbody>
        <% @user.each do |u| %>
          <%= render :partial => 'user', :locals => {:u => u} %>
        <% end %>
      </tbody>
    </table>
  <% else %>
   <table id="example1" class="table table-striped table-hover table-responsive">
      <thead>
        <tr id="">
          <td colspan="5">No Record!</td>
        </tr>
      </thead>
    </table>
  <% end %>
</div>
<%= paginate @user %>

app/views/admin/reports/delete_item.js.erb
$("#item<%=@item.id%>").replaceWith("<%= j render :partial => 'item', :locals => {i: @item} %>");

app/views/admin/reports/delete_user.js.erb
$("#user<%=@user.id%>").replaceWith("<%= j render :partial => 'user', :locals => {u: @user} %>");

app/views/admin/reports/edit_user.js.erb
<% cancel ||= params[:cancel] %>
<% if (cancel) %>
$("#user<%=@user.id%>").replaceWith("<%= j render :partial => 'user', :locals => {u: @user} %>")
<% else %>
$("#user<%=@user.id%>").html("<%= j render :partial => 'form_user' %>")
<% end %>

app/views/admin/reports/filter_item.js.erb
$(".filter-content").html("<%= j render :partial => 'item_list'%>");

app/views/admin/reports/filter_user.js.erb
$(".filter-content").html("<%= j render :partial => 'user_list'%>");

app/views/admin/reports/option_item.js.erb
$(".filter-content").html("<%= j render :partial => 'item_list'%>");
$(".sort_filter").val("<%= @state %>");

app/views/admin/reports/update_item.js.erb
$("#item<%=@item.id%>").replaceWith("<%= j render :partial => 'item', :locals => {i: @item} %>");

app/views/admin/reports/update_user.js.erb
$("#user<%=@user.id%>").replaceWith("<%= j render :partial => 'user', :locals => {u: @user} %>");